# Generated by Django 3.0.7 on 2020-07-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posthog', '0069_auto_20200714_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slack_message_format',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
